name: Build and deploy Python app to Azure Web App - fraud-api-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Fixes the Node.js deprecation warning by opting into the newer runner environment
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create venv and Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
                
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/
            !.github/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./release  # Download to a specific subfolder

      - name: Zip artifact for deployment
        run: |
          cd release
          zip -r ../release.zip .  # Zip everything inside the folder, not the folder itself

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ACFAE553BB2842B5A78F5E494E3618E3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3C8EAB25F24E4A5D9F824245B8D46935 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F78D78DB330A4A97BBEAE0B9CB3D1D0F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fraud-api-app'
          slot-name: 'Production'
          package: release.zip  # Deploy the zip file directly